# Generated by Django 4.0.8 on 2023-01-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('country_code', models.CharField(blank=True, help_text='standard country code extension', max_length=5, verbose_name='Country Code')),
                ('phone_number', models.CharField(help_text='10 digit valid phone number', max_length=10, verbose_name='Phone Number')),
                ('first_name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('mpin_set', models.BooleanField(default=False, help_text='is Mpin set', verbose_name='is_Mpin_Set')),
                ('mpin', models.CharField(help_text='Users secured code stored as hash', max_length=128, verbose_name='User Mpin')),
                ('kyc_verified', models.BooleanField(default=False, help_text='is Mpin set', verbose_name='is_Kyc_Verified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, help_text='standard country code extension', max_length=5, verbose_name='Country Code')),
                ('phone_number', models.CharField(help_text='10 digit valid phone number', max_length=10, verbose_name='Phone Number')),
                ('code', models.IntegerField(help_text='6 digit unique code', verbose_name='Text Code')),
                ('count', models.IntegerField(default=0, help_text='count of no of attempts made to send unique code', verbose_name='Retry Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('REFRESH', 'Refresh Token Type')], default='REFRESH', max_length=10)),
                ('token', models.CharField(help_text='Users secured token', max_length=128, verbose_name='User Token')),
                ('expiry', models.DateTimeField(help_text='Token expiry time', verbose_name='Token Expiry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='core.customuser', verbose_name='User Token')),
            ],
        ),
    ]
