# Generated by Django 4.0.8 on 2023-01-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='10 digit valid phone number', max_length=10, unique=True, verbose_name='Phone Number'),
        ),
    ]
