# Generated by Django 4.0.8 on 2023-02-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbxuser',
            name='refered_by_user_id',
            field=models.IntegerField(blank=True, help_text='refered by user_id', null=True, verbose_name='Refered By'),
        ),
    ]
