# Generated by Django 4.0.8 on 2023-01-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mpin',
            field=models.CharField(blank=True, help_text='Users secured code stored as hash', max_length=128, verbose_name='User Mpin'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(help_text='10 digit valid phone number', max_length=10, unique=True, verbose_name='Phone Number'),
        ),
    ]
