# Generated by Django 4.0.8 on 2023-01-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_mpin_alter_otp_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(help_text='10 digit valid phone number', max_length=10, verbose_name='Phone Number'),
        ),
    ]
